apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

# Urls de app noticias
urlpatterns = [

    path('', views.inicio, name="inicio"),

    # url para el detalle de la noticia por pk
    path('inicio<int:pk>', views.Inicio_Noticias, name='inicio'),

    # url del formulario de contacto
    path('contacto', views.contacto, name="contacto"),

    path ('comentario' , views.Comentar_Noticia, name='comentar')


]

apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [

    path('registro/', views.Registro.as_view(), name="registro"),

]

blog/urls.py
from django.contrib import admin
# importamos include para poder trabajar con las urls de noticias
from django.urls import path, include
# from apps.noticias import views
from . import views

# url del login
from django.contrib.auth import views as auth
from django.conf.urls.static import static

from django.conf import settings

# URL PRINCIPAL
urlpatterns = [
    # path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    # path para la url de la vista de home
    path('', views.home, name="home"),
    # path tiene 3 parametros direccion url, funcion de la vista(views),
    # path de nosotros
    path('nosotros/', views.nosotros, name="nosotros"),
    path ('contacto/',views.contacto, name="contacto"),
    # ---------- URL APP NOTICIA-----------
    path('noticia/', include('apps.noticias.urls')),

    # LOGIN
    # path('usuarios/login', views.login, name='login')
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    # ultimo error de la clase solucionado
    # path('logout/', auth.LoginView.as_view(), name='logout'),
    # cambiar LoginView por LogoutView
    path('logout/', auth.LogoutView.as_view(), name='logout'),

    # Registro
    path('usuarios/', include('apps.usuarios.urls')),

    
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nombre


class Noticia(models.Model):
    titulo = models.CharField(max_length=150)
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='noticias')
    categoria_noticia = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.titulo


class Contacto(models.Model):
    nombre = models.CharField(max_length=60)
    correo = models.EmailField()
    asunto = models.CharField(max_length=40)
    texto = models.TextField()

    def __str__(self) -> str:
        return self.nombre



#

class Comentario(models.Model):
    texto = models.TextField(null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

def __str__(self) -> str:
    return f"{self.noticia} {self.texto}"

apps/usuarios/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
    pass

apps/noticias/forms.py
from django import forms
from .models import Contacto


class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = "__all__"

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Ingrese su contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Vuelva a ingresar su contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

apps/noticias/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Noticia, Categoria, Contacto , Comentario
# Create your views here.

from .forms import ContactoForm

from django.urls import reverse_lazy

# def inicio(request):
#     return HttpResponse("<h1>HOLA MUNDO</h1> <h2> desde django</h2>")

# decorador para ver las noticias solamente como usuario logueado
from django.contrib.auth.decorators import login_required

# uso de decorador para verificar logeo de usuario y poder ver noticia


@login_required
def inicio(request):
    # obtener todas las noticias y mostrar en el inicio.html
    # ctx = {}
    # # clase.objetcs.all()==> select * from noticia
    # noticia = Noticia.objects.all()
    # ctx["noticias"] = noticia
    # return render(request, 'noticias/inicio.html', ctx)
    contexto = {}
    id_categoria = request.GET.get('id', None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia=id_categoria)
    else:
        n = Noticia.objects.all()  # una lista

    contexto['noticias'] = n

    cat = Categoria.objects.all().order_by('nombre')
    contexto['categorias'] = cat

    return render(request, 'noticias/inicio.html', contexto)


@login_required
def Inicio_Noticias(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk=pk)
    contexto['noticia'] = n

    c = Comentario.objects.filter(noticia=n)
    contexto['comentarios'] = c

    return render(request, 'noticias/inicio.html', contexto)


# ClaseName.objects.all()[0:2]              select * from noticias
# ClaseName.objects.get(pk = 1)        select * from noticias where id = 1
# ClaseName.objects.filter(categoria)  select * from noticias where categoria = deportes


def contacto(request):
    data = {
        'form': ContactoForm()
    }
    if request.method == 'POST':
        ContactoForm(data=request.POST).save()

    return render(request, 'contacto', data)

@login_required 
def Comentar_Noticia (request):
    comentario = request.POST.get('comentario', None)
    user = request.user
    noti = request.POST.get('id_noticia', None)
    noticia = Noticia.objects.get(pk=noti)
    coment = Comentario.objects.create(
        usuario=user, noticia=noticia , texto=comentario)
    return redirect(reverse_lazy('noticias:inicio', kwargs={"pk":noti}))

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.
# importts
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import RegistroForm


class Registro(CreateView):
    # forms django
    form_class = RegistroForm
    success_url = reverse_lazy('login')
    template_name = 'usuarios/registro.html'

blog/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def nosotros(request):
    return render(request, 'nosotros.html', {
        "saludo": "Hola mundo",
        "nombre": "Soy el contexto",
        "autor": "Dani"
    })

def index(request) :
    return render (request,'index.html') 


# def login(request):
#     if request.method == 'POST':
#         email = request.POST.get('email')
#         password = request.POST.get('password')

#         print("esto es el correo ingresado por el form login", email)
#         print("esto es el contraseña ingresado por el form login", password)

#     return render(request, 'usuarios/login.html')
def contacto (request):
    return render(request, 'contacto.html',)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- CSS PROPIO -->
    <link rel="stylesheet" href="{% static 'assets/main.css'%}">
    <link rel="shotrcut icon" href="{% static 'img/diamond.png'%}">
    <title> Hard Pixel </title>
</head>

<body class="contenedor" style="background-color: #000;" >

    <div>
        <a href="{% url 'nosotros' %}"> nosotros</a>
        <a href="{% url 'home' %}"> home</a>
        <a href="{% url 'noticias:inicio' %}"> noticia</a>

        {% if user.is_authenticated %}
        <p> Bienvenido {{ user.username }}</p>
        <a href="{% url 'logout' %}"> cerrar sesion</a>
        {% else %}
        <a href="{% url 'login' %}"> iniciar sesion</a>
        <a href="{% url 'usuarios:registro' %}">Registrar</a>

        {% endif %}
    </div>

    {% block contenido %}

    {% endblock contenido%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block titulo%} contacto {%endblock titulo%}

{% block contenido%}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS Files -->
  <link href="{% static '/assets/css/variables.css' %}" rel="stylesheet">
  <link href="{% static '/assets/css/main.css'   %}" rel="stylesheet">

  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="/#" class="logo d-flex align-items-center">
       <img src="{% static 'img/diamond.png'%}" alt=""> 
        <h1>HARD PIXEL</h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/#">Inicio</a></li>
          
          <li><a href="/noticia">Noticias</a></li>
          <li class="dropdown"><a href="category.html"><span>Categorias</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="/noticia">Mostrar Todo</a></li>
              <li><a href="#">Mejores juegos 2023</a></li>
                <ul>
                  
                  
                </ul>
              </li>
              <li><a href="#">Proximos juegos</a></li>
              <li><a href="#">Tiendas gaming</a></li>
              <li><a href="#">Mejores paginas para juegos</a></li>
            </ul>
          </li>

          <li><a href="/nosotros">Sobre Nosotros</a></li>
          <li><a href="/contacto">Contactanos</a></li>
        </ul>
        {% if user.is_authenticated %}
        <p style=color:#d81ce9; 
        >  Bienvenido {{ user.username }}</p> 
        <a href="{% url 'logout' %}"> Cerrar sesion</a>
        {% else %}
        <a href="{% url 'login' %}">Iniciar sesion</a>
        <a href="{% url 'usuarios:registro' %}">Registrarse</a>

        {% endif %}
      </nav><!-- .navbar -->

      <div class="position-relative">
        <a href="#" class="mx-2"><span class="bi-facebook" style="color:#d81ce9"></span></a>
        <a href="#" class="mx-2"><span class="bi-twitter"style="color:#d81ce9"></span></a>
        <a href="#" class="mx-2"><span class="bi-instagram"style="color:#d81ce9"></span></a>

        <a href="#" class="mx-2 js-search-open"><span class="bi-search"style="color:#d81ce9"></span></a>
        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="search-result.html" class="search-form">
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->
<section style="background-color: #070607;">
  <main id="main">
    <section id="contact" class="contact mb-5">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-12 text-center mb-5">
            <h1 class="page-title" style="color: #d81ce9;">Contactanos</h1>
          </div>
        </div>

        <div class="row gy-4">

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-geo-alt" style="color: #d81ce9;"></i>
              <h3 style="color: #d81ce9;">Direccion</h3>
              <address style="color: #6102fa;">EJEMPLO , Resistencia, Argentina</address>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item info-item-borders">
              <i class="bi bi-phone" style="color: #d81ce9;"></i>
              <h3 style="color: #d81ce9;">Telefono</h3>
              <p><a href="tel:+155895548855" style="color: #6102fa;">+54 EJEMPLO</a></p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-envelope" style="color: #d81ce9;"></i>
              <h3 style="color: #d81ce9;">Email</h3>
              <p><a href="mailto:info@ejemplo.com" style="color: #6102fa;">info@ejemplo.com</a></p>
            </div>
          </div><!-- End Info Item -->

        </div>
    
<section>

<form  action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>


</section>
        <div class="form mt-5" >
          
          <form action="forms/contact.php" style="background-color: #070607 ;" method="post" role="form" class="php-email-form">
            <div class="row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Su nombre" required>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Su correo" required>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Tema" required>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" placeholder="Mensaje" required></textarea>
            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center"><button type="submit" style="background-color: #d81ce9;">Enviar mensaje</button></div>
          </form>
        </div><!-- End Contact Form -->
    
      </div>
    </section>

  </main><!-- End #main -->
</section>
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">

        <div class="row g-5">
          <div class="col-lg-4">
            <h3 class="footer-heading">Sobre nosotros</h3>
            <p>Somos un grupo dedicados al gaming </p>
            <p><a href="/nosotros" class="footer-link-more">Leer mas</a></p>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Navegacion</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="noticia"><i class="bi bi-chevron-right"></i> Noticias</a></li>
              <li><a href="about.html"><i class="bi bi-chevron-right"></i> Sobre nosotros</a></li>
              <li><a href="contact.html"><i class="bi bi-chevron-right"></i> Contactanos</a></li>
            </ul>
          </div>
          <div class="col-6 col-lg-2">
            <h3 class="footer-heading">Categorias</h3>
            <ul class="footer-links list-unstyled">
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Juegos Indies</a></li>
              <li><a href="category.html"><i class="bi bi-chevron-right"></i> Proximos juegos</a></li>

            </ul>
          </div>

          

          </div>
        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">

        <div class="row justify-content-between">
          <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
            <div class="copyright">
              © Copyright <strong><span></span></strong>. All Rights Reserved
            </div>

            <div class="credits">
              
              
            </div>

          </div>

          <div class="col-md-6">
            <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            </div>

          </div>

        </div>

      </div>
    </div>

  </footer>


  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{%static 'assets/vendor/aos/aos.js' %}"></script>
  

  <!-- Template Main JS File -->
  <script src="{%static 'assets/js/main.js' %}"></script>

</body>

</html>
{% endblock contenido%}

templates/contacto/formulario.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%} Contacto{%endblock titulo%}
<h1>Contacto</h1>
{% block contenido%}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock contenido%}

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%}Noticia{%endblock titulo%}

{% block contenido%}

<h1>{{noticia}}</h1>
<img src="{{noticia.imagen.url}}" alt="" width="500" height="500">
<p>{{noticia.cuerpo}}</p>
<p>{{noticia.fecha}}</p>
<p>{{noticia.categoria_noticia}}</p>

<form action=" {% url 'noticias:comentar' %} " method="POST"> {% csrf_token %}

<textarea name="comentario" id="" cols="30" rows="3"></textarea>
<input type="text" name="id_noticia" value="{{ noticia.pk}}" hidden="">
<input type="submit" value="comentar">

</form>
<h3>comentarios</h3>
{% for comentario in comentario %}

<p><strong>{{ comentario.usuario}}</strong> {{ comentario.fecha}} </p>
<p>Comentario: {{comentario.text}} </p>


{% endfor %}


{% endblock contenido%}

templates/noticias/inicio2.html
{% extends 'base.html' %}
{% load static %}

{% block titulo%} noticias {% endblock titulo %}

{% block contenido%}
<h2>Soy las noticias</h2>

<a href="{% url 'noticias:inicio' %}"> Todas</a>
{% for c in categorias %}
<a href="?id={{c.pk}}">{{c.nombre}}</a>
{% endfor %}

{% for noticia in noticias %}

<h2>titulo:<a href="{% url 'noticias:detalle' noticia.pk %}"> <strong>{{ noticia.titulo }}</strong></a></h2>
<p>cuerpo: {{ noticia.cuerpo }}</p>
<p>{{noticia.fecha}}</p>
<p>categoria: {{noticia.categoria_noticia}}</p>
<img src="{{ noticia.imagen.url }}" alt="" width="200">

{% endfor %}

{% endblock contenido%}

templates/usuarios/login.html
{% extends 'home.html' %}
{% load static %}

{% block contenido%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS Files -->
  <link href="{% static '/assets/css/variables.css' %}" rel="stylesheet">
  <link href="{% static '/assets/css/main.css'   %}" rel="stylesheet">

  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="/#" class="logo d-flex align-items-center">
       <img src="{% static 'img/diamond.png'%}" alt=""> 
        <h1>HARD PIXEL</h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/#">Inicio</a></li>
          
          <li><a href="/noticia">Noticias</a></li>
          <li class="dropdown"><a href="category.html"><span>Categorias</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="/noticia">Mostrar Todo</a></li>
              <li><a href="#">Mejores juegos 2023</a></li>
                <ul>
                  
                  
                </ul>
              </li>
              <li><a href="#">Proximos juegos</a></li>
              <li><a href="#">Tiendas gaming</a></li>
              <li><a href="#">Mejores paginas para juegos</a></li>
            </ul>
          </li>

          <li><a href="/nosotros">Sobre Nosotros</a></li>
          <li><a href="/contacto">Contactanos</a></li>
        </ul>
        {% if user.is_authenticated %}
        <p style=color:#d81ce9; 
        >  Bienvenido {{ user.username }}</p> 
        <a href="{% url 'logout' %}"> Cerrar sesion</a>
        {% else %}
        <a href="{% url 'login' %}">Iniciar sesion</a>
        <a href="{% url 'usuarios:registro' %}">Registrarse</a>

        {% endif %}
      </nav><!-- .navbar -->

      <div class="position-relative">
        <a href="#" class="mx-2"><span class="bi-facebook" style="color:#d81ce9"></span></a>
        <a href="#" class="mx-2"><span class="bi-twitter"style="color:#d81ce9"></span></a>
        <a href="#" class="mx-2"><span class="bi-instagram"style="color:#d81ce9"></span></a>

        <i class="bi bi-list mobile-nav-toggle"></i>

        <!-- ======= Search Form ======= -->
        <div class="search-form-wrap js-search-form-wrap">
          <form action="search-result.html" class="search-form">
            <span class="icon bi-search"></span>
            <input type="text" placeholder="Search" class="form-control">
            <button class="btn js-search-close"><span class="bi-x"></span></button>
          </form>
        </div><!-- End Search Form -->

      </div>

    </div>

  </header><!-- End Header -->

<link rel="stylesheet" href="{% static '/assets/css/login.css'   %}">
<section-header style="background-color: #000 !important;">
<div class="container px-4 py-5 mx-auto">
    <div class="card card0">
        <div class="d-flex flex-lg-row flex-column-reverse">
            <div class="card card1">
                <div class="row justify-content-center my-auto">
                    <div class="col-md-8 col-10 my-5">
                        <div class="row justify-content-center px-3 mb-3">
                            <img id="logo" src="{% static 'img/diamond.png' %}">
                        </div>  
                        <h3 class="mb-5 text-center heading">SOMOS <br> HARD PIXEL</h3>

                        <h6 class="msg-info">Iniciar sesion</h6>
                        <form method="POST">{% csrf_token %}
							{{ form.errors }}
                        <div class="form-group">
                            <input type="text" class="form-control-label text-muted" name="username" placeholder="usuario">

                        </div>

                        <div class="form-group">
                            <input class="form-control-label text-muted" type="password" name="password" placeholder="contraseña">

                        </div>

                        <div class="row justify-content-center my-3 px-3">
                            <input type="submit" value="enviar">


                        </div>

                        <div class="row justify-content-center my-2">
                        </div>
                    </div>
                </div>
                <div class="bottom text-center mb-5">
                    <h5 class="sm-text mx-auto mb-3">No tienes cuenta?<a style="background-color: #f3f3f3;" class="btn btn-white ml-2 "href="{% url 'usuarios:registro' %}" >Registrate</a></h5>
                </div>
            </div>
            <div class="card card2">
                <div class="my-auto mx-md-5 px-md-5 right">
                    <h3 class="text-white" style="font-size: 250%;">Mas que una compania</h3>
                    <small class="text-white" style="font-size:200%;">Las mejores novedades sobre el mundo del gaming</small>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
</form>
<script src="{%static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{%static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{%static 'assets/vendor/aos/aos.js' %}"></script>
  

  <!-- Template Main JS File -->
  <script src="{%static 'assets/js/main.js' %}"></script>

  {% endblock contenido%}

templates/usuarios/registro1.html
{% extends 'base.html' %}
{% load static %}

{% block contenido%}
<h1>Registro</h1>
<form action="" method="post"> {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

{% endblock contenido%}